### ISSUE TITLE
[1.12.2] Conflict with Foamfix & Refined Storage. *Unable to craft Lapis Blocks, Light Blue Dyes, etc.*

### ISSUE THREAD

**Issue by SonicX8000** [ganymedes01/TheErebus#603]
Referred Issue:
https://github.com/asiekierka/FoamFix/issues/141

Minecraft: 1.12.2
Forge: 14.23.3.2673

Mods:
Erebus-1.0.22
foamfix-0.9.8-1.12.2-anarchy OR foamfix-0.9.8-1.12.2-law
refinedstorage-1.5.33
refinedstorageaddons-0.3

-----
For some weird reason having Erebus installed with the above mods breaks certain vanilla recipes, such as making Lapis Blocks or Blue Dyes. If Erebus isn't installed... the recipes are fine.

If using the Lawful version of Foamfix or... if using Anarchy but with it's 'cacheShiftClickCrafting' disabled the recipe will work correctly for some crafting means... but... it won't work for certain mods that have different crafting means, such as Refined Storage's Crafting Grid.

Using NoMoreRecipeConflict, which is a mod that allows you to cycle between items that have conflicting recipes... it shows a broken Lapis Block recipe and then the correct one if I click on the arrow. Sometimes if I shift-click the blank space for the broken recipe it'll let me craft the items but not all the time.

Some other crafting means like using the Wireless Crafting Terminal from Refined Storage Addons the recipes work correctly.

**Comment by asiekierka** [comment]
Happens without FoamFix too, except not on the vanilla crafting grid. I have a feeling FastWorkbench and FoamFix both break it on the vanilla crafting gird.

**Comment by vadis365** [comment]
I have no idea.
Is this Erebus or not?

**Comment by SonicX8000** [comment]
Using only these mods...
Erebus-1.0.22
refinedstorage-1.5.33

This is what happens when using the Crafting Grid from Refined Storage to craft Lapis Blocks.
![](https://cdn.discordapp.com/attachments/377171551155650560/439150865656446977/refinedstorageerebusx.PNG)
Left: Erebus + Refined Storage, recipe doesn't output Laplis Block.
Right: Refined Storage, recipe outputs Laplis Blocks.
*Note: I shrunk the massive size of the crafting grid just so the image wasn't huge.*

Is it possible that this might be on Refined Storage's end?

**Comment by asiekierka** [comment]
Doesn't this happen with other mods too? Just about anything that's not the vanilla crafting table.

Remember: lapis is a dye!

**Comment by SonicX8000** [comment]
As far as I know, having around 270+ mods added... removing Erebus from the list and Refined Storage's Crafting Gird & Vanilla Crafting works as intended so it shouldn't be any other mods. Here's an image.
![](https://cdn.discordapp.com/attachments/377171551155650560/441757265263984662/modsbutnoerebus.PNG)
Erebus isn't loaded after taking the image alongside several mods being loaded thus Lapis Blocks & such are craftable.

If Erebus is loaded... the Lapis Blocks & such won't be craftable.
*Changing Foamfix's 'cacheShiftClickCrafting' to false will allow Vanilla Crafting Tables to craft Lapis Blocks.

There is a way to get around this if I make a pattern to auto-craft the items for the Crafting Grid, but... still.

**Comment by vadis365** [comment]
![image](https://user-images.githubusercontent.com/6518708/39790426-f773689e-532d-11e8-9674-10f6ff62f6b8.png)
Just Erebus loaded.
I have fixed a derp in my recipe registry - may have been that - will push an update out in a day or so and hopefully one less thing will be broken in this mess of a mod. ;)

**Comment by vadis365** [comment]
Closing because this is as stale as my foot odour.

**Comment by asiekierka** [comment]
Too much information.

**Comment by SonicX8000** [comment]
Been awhile and I'm not sure if I should make a new issue being that it's the same issue as this one but anyway... I gave the update a try just to see if this issue was fixed but the recipe bug still occurs. It doesn't seem that Foamfix was causing issues.

Anyway... using a Vanilla Crafting Table alongside the "NoMoreRecipeConflict" mod, it'll show there being two recipes which both result in the same item/block being crafted, such as a Lapis Block or Light Blue Dye. If you... however attempting to craft it via other means such as Refined Storage's Crafting Grid... and try to craft a Lapis Block/Light Blue Dye... the first recipe shows nothing but if you cycle to the second recipe it'll show the item being craftable.

Erebus's Petrified Crafting Table also has the two recipes when attempting to craft Lapis Blocks or Light Blue Dyes. There may be other items but those are the only two that I ran into.

At the time of the test I was using...

Minecraft: 1.12.2
Forge: 14.23.5.2772

Mods:
Erebus-1.0.23
NoMoreRecipeConflict-0.10(1.12.2)

I think due to there being two recipes towards the same item is perhaps what causes foamfix/refined storage to not show the items being craftable. Here are some screenshots.

![](https://cdn.discordapp.com/attachments/377171551155650560/508495754915086357/erebusrecipebug.PNG)
This is with Erebus installed. There's two recipes despite it being the same item, first recipe tends to be glitched and show no item at certain other crafting means such as the Crafting Grid from Refined Storage.

![](https://cdn.discordapp.com/attachments/377171551155650560/508496021022572545/erebusnorecipebug.PNG)
This is without Erebus being installed. Only one recipe is listed and other crafting means will work as intended as it isn't grabbing the buggy recipe.

I hope this helps with narrowing down this bug.

**Comment by arkan501** [comment]
Can confirm, issue exists in 1.0.23, also the issue persists to Applied Energistics 2 and Tinker's Constructs crafting grids.

**Comment by SonicX8000** [comment]
Ah, I'm not the only one. Also... the bug still exists in 'Erebus-1.0.24.jar'.

**Comment by vadis365** [comment]
Hotfixed in 1.0.25 - we did it \o/

**Comment by SonicX8000** [comment]
Can confirm that this issue is fixed in 1.0.25. Only one recipe shows instead of two and I'm able to craft Lapis Blocks + Dyes without any problems now for non-vanilla crafting such as Refined Storage.
